export type RemediationStep = {
  id: string;
  title: string;
  detail: string;
};

const STEPS: Record<string, RemediationStep> = {
  "change-password": {
    id: "change-password",
    title: "Change the password on the breached service",
    detail: "Use a new, unique password generated by a password manager.",
  },
  "reused-passwords": {
    id: "reused-passwords",
    title: "Replace the password everywhere it was reused",
    detail: "Attackers try leaked passwords on other sites (credential stuffing).",
  },
  "enable-mfa": {
    id: "enable-mfa",
    title: "Turn on multi-factor authentication",
    detail: "An authenticator app or security key stops logins with a stolen password.",
  },
  "revoke-sessions": {
    id: "revoke-sessions",
    title: "Sign out of all sessions and revoke tokens",
    detail: "Stolen session tokens keep working until they are revoked.",
  },
  "contact-bank": {
    id: "contact-bank",
    title: "Alert your bank and watch statements",
    detail: "Ask for a new card number if card or bank data was exposed.",
  },
  "credit-freeze": {
    id: "credit-freeze",
    title: "Place a fraud alert or credit freeze",
    detail: "Government IDs and dates of birth are used to open accounts in your name.",
  },
  "security-questions": {
    id: "security-questions",
    title: "Change security questions and answers",
    detail: "Treat old answers as public. Use random answers stored in a password manager.",
  },
  "phishing-watch": {
    id: "phishing-watch",
    title: "Expect targeted phishing",
    detail: "Leaked names, phone numbers and addresses make scam messages look real. Verify before you click.",
  },
};

/** Recommended response steps for the data classes exposed by a breach. */
export function remediationSteps(dataClasses: readonly string[]): RemediationStep[] {
  const has = (...names: string[]) => names.some((n) => dataClasses.includes(n));
  const ids: string[] = [];
  if (has("Passwords", "Password hints")) ids.push("change-password", "reused-passwords", "enable-mfa");
  if (has("Auth tokens")) ids.push("revoke-sessions");
  if (has("Credit cards", "Partial credit card data", "Bank account numbers", "Payment histories", "Account balances")) ids.push("contact-bank");
  if (has("Social security numbers", "Government issued IDs", "Passport numbers", "Dates of birth")) ids.push("credit-freeze");
  if (has("Security questions and answers")) ids.push("security-questions");
  ids.push("phishing-watch");
  if (!ids.includes("enable-mfa")) ids.push("enable-mfa");
  return [...new Set(ids)].map((id) => STEPS[id]);
}

export function isKnownStep(id: string): boolean {
  return id in STEPS;
}
